#!/bin/zsh

set -o nounset
set -o errexit

DRIVE=nvme0n1
BOOTPART=ef00
HOSTNAME=dashie

hostname $HOSTNAME

dd if=/dev/zero of=/dev/$DRIVE bs=1M count=1k
echo "2\nn\n\n+128M\n+384M\n${BOOTPART}\nn\n\n\n\n\np\nw\ny\n" | gdisk /dev/$DRIVE

mkfs.vfat -F 32 /dev/${DRIVE}p1

mkfs.btrfs -L broot /dev/${DRIVE}p2

mount /dev/${DRIVE}p2 /mnt
cd /mnt
btrfs subvolume create @
btrfs subvolume create @home
cd /root
umount /mnt 

mount -o noatime,nodiratime,subvol=@ /dev/${DRIVE}p2 /mnt
mkdir /mnt/boot
mkdir /mnt/home
mount -o noatime,nodiratime,subvol=@home /dev/${DRIVE}p2 /mnt/home
mount /dev/${DRIVE}p1 /mnt/boot

pacstrap /mnt base base-devel zsh

genfstab -U -p /mnt >> /mnt/etc/fstab

arch-chroot /mnt

