#!/bin/zsh

function error_message {
    echo "\nerror: $1"
    exit 1
}

DRY=true

echo "\nset -k"
$DRY || set -k


echo "\nDIRNAME=$(dirname $0)"
DIRNAME=$(dirname $0)

echo "\nsource \"$DIRNAME/arch-config\""
source "$DIRNAME/arch-config" || error_message "can't find config file"
echo "\nsource \"$DIRNAME/functions.sh\""
source "$DIRNAME/functions.sh" || error_message "can't find functions.sh file"



echo "\nmodprobe raid1"
$DRY || modprobe raid1
echo "\nmodprobe dm-mod"
$DRY || modprobe dm-mod

	

for i in ${DRIVESARR[*]}; do
	DEV="/dev/sd${i}"
	echo "\n# clearing device: $DEV"
	echo "\ndd if=/dev/zero of=$DEV bs=512 count=$CLEAR_BLOCKS"
	$DRY || dd if=/dev/zero of=$DEV bs=512 count=$CLEAR_BLOCKS
	echo "\ndd if=/dev/zero of=$DEV bs=512 seek=$(( $(blockdev --getsz $DEV) - $CLEAR_BLOCKS )) count=$CLEAR_BLOCKS"
	$DRY || dd if=/dev/zero of=$DEV bs=512 seek=$(( $(blockdev --getsz $DEV) - $CLEAR_BLOCKS )) count=$CLEAR_BLOCKS
done


for i in ${BCACHE_DRIVESARR[*]}; do
	DEV="/dev/sd${i}"
	echo "\n# clearing device: $DEV"
	echo "\ndd if=/dev/zero of=$DEV bs=1M"
	$DRY || dd if=/dev/zero of=$DEV bs=1M
done


	#####
	# 1 - ef00 for efi systems, ef02 on bios systems with gpt
	# 2 - /boot can't be in raid5 array
	# 3 - everything else will be on the lvm on top of raid5
	#####


#mkfs.btrfs -d raid1 /dev/sd[${DRIVES}]

if [[ $BIOS = "efi" ]]; then
	echo "\necho \"2\\\no\\\ny\\\nn\\\n\\\n\\\n+100M\\\nef00\\\nn\\\n\\\n\\\n+512M\\\n\\\nn\\\n\\\n\\\n+${ROOTSIZE}\\\n8300\\\nn\\\n\\\n\\\n\\\nbf00\\\np\\\nw\\\ny\\\n\" | gdisk /dev/sd${DRIVESARR[1]}"
	$DRY || echo "\n2\no\ny\nn\n\n\n+100M\nef00\nn\n\n\n+200M\n\nn\n\n\n+${SWAPSIZE}\nfd00\nn\n\n\n+${ROOTSIZE}\nfd00\nn\n\n\n\nbf00\np\nw\ny\n" | gdisk /dev/sd${DRIVESARR[1]}

	echo "\necho \"2\\\no\\\ny\\\nn\\\n\\\n\\\n+${SWAPSIZE}\\\nfd00\\\nn\\\n\\\n\\\n+${ZILSIZE}\\\nbf00\\\nn\\\n\\\n\\\n\\\nbf00\\\np\\\nw\\\ny\\\n\" | gdisk /dev/sd$BCACHE_DRIVESARR[1]"
	$DRY || echo "\n2\no\ny\nn\n\n\n+100M\nef00\nn\n\n\n+200M\n\nn\n\n\n+${SWAPSIZE}\nfd00\nn\n\n\n+${ROOTSIZE}\nfd00\nn\n\n\n\nbf00\np\nw\ny\n" | gdisk /dev/sd$BCACHE_DRIVESARR[1]
else
	echo "\n2\no\ny\nn\n\n\n+100M\nef02\nn\n\n\n+100M\nfd00\nn\n\n\n-50M\nfd00\np\nw\ny\n" | gdisk /dev/sd${DRIVESARR[1]}
fi

	# copy partition table to other hard drives

echo "\nsgdisk --backup=table /dev/sd${DRIVESARR[1]}"
$DRY || sgdisk --backup=table /dev/sd${DRIVESARR[1]}
for i in ${DRIVESARR[*]}
do
	echo "\nsgdisk --load-backup=table /dev/sd${i}" 
	$DRY || sgdisk --load-backup=table /dev/sd${i} 
        echo "partprobe /dev/sd${i}"
        $DRY || partprobe /dev/sd${i}
done

echo "\nsgdisk --backup=table /dev/sd$BCACHE_DRIVESARR[1]"
$DRY || sgdisk --backup=table /dev/sd$BCACHE_DRIVESARR[1]
for i in ${BCACHE_DRIVESARR[*]}
do
	echo "\nsgdisk --load-backup=table /dev/sd${i}" 
	$DRY || sgdisk --load-backup=table /dev/sd${i} 
        echo "partprobe /dev/sd${i}"
        $DRY || partprobe /dev/sd${i}
done


echo "\nmdadm --create /dev/md0 --level=1 --metadata=1.2 --raid-devices=${#BCACHE_DRIVES} /dev/sd[${BCACHE_DRIVES}]1"
$DRY || mdadm --create /dev/md0 --level=1 --metadata=1.2 --raid-devices=${#BCACHE_DRIVES} /dev/sd[${BCACHE_DRIVES}]1







for i in ${DRIVESARR[*]}
do
	echo "\nmkfs.vfat -F 32 /dev/sd${i}1"
	$DRY || mkfs.vfat -F 32 /dev/sd${i}1
	echo "\nmkfs.ext3 -L boot /dev/sd${i}2"
	$DRY || mkfs.ext3 -L boot /dev/sd${i}2
done


echo "\nmkswap -L swap_${i} /dev/md0"
$DRY || mkswap -L swap_${i} /dev/md0
echo "\nswapon /dev/md0"
$DRY || swapon /dev/md0


echo "\nmkfs.btrfs -f -d radi1 -L root /dev/sd[${DRIVES}]3"
$DRY || mkfs.btrfs -f -d radi1 -L root /dev/sd[${DRIVES}]3

echo "\nmount /dev/sd${DRIVESARR[1]}3 /mnt/"
$DRY || mount /dev/sd${DRIVESARR[1]}3 /mnt/

echo "\nmkdir /mnt/boot"
$DRY || mkdir /mnt/boot
echo "\nmount  /dev/sd${DRIVESARR[1]}2 /mnt/boot"
$DRY || mount  /dev/sd${DRIVESARR[1]}2 /mnt/boot



echo "\nmkdir /mnt/boot/efi"
$DRY || mkdir /mnt/boot/efi
echo "\nmount /dev/sd${DRIVESARR[1]}1 /mnt/boot/efi"
$DRY || mount /dev/sd${DRIVESARR[1]}1 /mnt/boot/efi


echo "\npacstrap /mnt base base-devel zsh"
$DRY || pacstrap /mnt base base-devel zsh

echo "\ngenfstab -U -p /mnt >> /mnt/etc/fstab"
$DRY || genfstab -U -p /mnt >> /mnt/etc/fstab

#cp install-arch-raid-chroot /mnt/
#chmod 755 /mnt/install-arch-raid-chroot

echo "\nch -r /root/arch /mnt/root/"

echo "\narch-chroot /mnt" #/install-arch-raid-chroot
$DRY || arch-chroot /mnt #/install-arch-raid-chroot




