#!/bin/zsh

set -k

HOSTNAME="doghouse"
NEWUSERNAME=zidar
USERPASS=pass
ROOTPASS=pass


install_yaourt

hostname $HOSTNAME
echo ${HOSTNAME} > /etc/hostname



sed -i 's/#sl_SI.UTF-8/sl_SI.UTF-8/' /etc/locale.gen
sed -i 's/#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
sed -i 's/#en_GB.UTF-8/en_GB.UTF-8/' /etc/locale.gen
locale-gen




echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

echo KEYMAP=us > /etc/vconsole.conf
sed -i '$ a FONT=' /etc/vconsole.conf
sed -i '$ a FONT_MAP=' /etc/vconsole.conf




pacman -S --noconfirm ntp 
ln -s /usr/share/zoneinfo/Europe/Ljubljana /etc/localtime
ntpd -qg
hwclock --systohc --utc



sed -i "s/\#\[multilib\]/\[multilib\]\nInclude = \/etc\/pacman\.d\/mirrorlist/g" /etc/pacman.conf 



pacman -Syy
pacman -S --noconfirm bash-completion vim sudo git openssh dosfstools wget htop
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers

# 
# mkinitcpio -p linux
# bootctl install
# echo "title          Arch Linux" > /boot/loader/entries/arch.conf
# echo "linux          /vmlinuz-linux" >> /boot/loader/entries/arch.conf
# echo "initrd         /initramfs-linux.img" >> /boot/loader/entries/arch.conf
# echo "options        root=UUID=<change me> rw" >> /boot/loader/entries/arch.conf
# 

pacman -S --noconfirm grub efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub


mkdir -p /boot/grub/locale
cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg




useradd -m -g users -G wheel,storage,power -s /bin/bash $NEWUSERNAME
echo "$NEWUSERNAME\n\n\n\n" | chfn $NEWUSERNAME

echo "${USERPASS}\n${USERPASS}" | passwd $NEWUSERNAME
echo "${ROOTPASS}\n${ROOTPASS}" | passwd root

systemctl enable sshd.service







pacman -S --noconfirm alsa-utils
pacman -S --noconfirm xorg-server xorg-xinit xorg-server-utils

# for ati:
# pacman -S --noconfirm xf86-video-ati

# for intel:
pacman -S --noconfirm xf86-video-intel 

# for nvidia:
# pacman -S --noconfirm xf86-video-nouveau 
# pacman -S --noconfirm nvidia 






pacman -S --noconfirm gnome gnome-extra 
pacman -S --noconfirm ttf-ubuntu-font-family ttf-liberation ttf-inconsolata ttf-droid ttf-linux-libertine ttf-dejavu ttf-bitstream-vera

systemctl enable gdm.service

pacman -S --noconfirm  networkmanager network-manager-applet
systemctl enable NetworkManager.service 



pacman -S --noconfirm  terminator blender gimp meld gitg smartmontools firefox rsync vlc pidgin deluge

pacman -R --noconfirm epiphany empathy gnome-chess gnome-mines gnome-sudoku gnome-tetravex gnome-robots gnome-klotski gnome-nibbles totem gnome-documents gnome-photos tracker evolution gnome-music gnome-online-miners bijiben


#
# > tune2fs -o journal_data_writeback /dev/sdXY
# data=writeback,noatime
#
