#!/bin/zsh

echo "looking for config"
[[ -a arch-config ]] || cd /root/arch
[[ -a arch-config ]] || { echo "no config found" ; exit }

echo "starting arch"

set -k
source arch-config

if [[ $BIOS == "efi" ]]; then
	modprobe efivars
fi



hostname $HOSTNAME
echo ${HOSTNAME} > /etc/hostname



sed -i 's/#sl_SI.UTF-8/sl_SI.UTF-8/' /etc/locale.gen
sed -i 's/#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
sed -i 's/#en_GB.UTF-8/en_GB.UTF-8/' /etc/locale.gen
locale-gen




echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

echo KEYMAP=us > /etc/vconsole.conf
sed -i '$ a FONT=' /etc/vconsole.conf
sed -i '$ a FONT_MAP=' /etc/vconsole.conf






pacman -S --noconfirm ntp 
ln -s /usr/share/zoneinfo/Europe/Ljubljana /etc/localtime
ntpd -qg
hwclock --systohc --utc



sed -i "s/\#\[multilib\]/\[multilib\]\nInclude = \/etc\/pacman\.d\/mirrorlist/g" /etc/pacman.conf 



pacman -Syy
pacman -S --noconfirm bash-completion vim sudo git openssh dosfstools wget htop
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers





mkinitcpio -p linux

if [[ $BIOS == "efi" ]]; then
	pacman -S --noconfirm efibootmgr grub-efi-x86_64
	grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch_grub --recheck --debug
else
	pacman -S --noconfirm grub-bios
	grub-install --recheck /dev/sda
fi

mkdir -p /boot/grub/locale
cp /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo

grub-mkconfig -o /boot/grub/grub.cfg










useradd -m -g users -G wheel,storage,power -s /bin/bash $NEWUSERNAME
echo "$NEWUSERNAME\n\n\n\n" | chfn $NEWUSERNAME

echo "${USERPASS}\n${USERPASS}" | passwd $NEWUSERNAME
echo "${ROOTPASS}\n${ROOTPASS}" | passwd root

systemctl enable sshd.service







pacman -S --noconfirm alsa-utils
pacman -S --noconfirm xorg-server xorg-xinit xorg-server-utils
pacman -S --noconfirm mesa

if [[ $VBOX == "yes" ]]; then
	pacman -S --noconfirm virtualbox-guest-utils
	modprobe -a vboxguest vboxsf vboxvideo
	echo 'vboxguest\nvboxsf\nvboxvideo' > /etc/modules-load.d/virtualbox.conf
else
	# for ati:
	# pacman -S --noconfirm xf86-video-ati 

	# for nvidia:
	# pacman -S --noconfirm xf86-video-nouveau 
	pacman -S --noconfirm nvidia 
fi







cd /tmp
wget https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
tar -xpvf package-query.tar.gz
cd package-query
makepkg -i --asroot --noconfirm

cd /tmp
wget https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz
tar -xpvf yaourt.tar.gz
cd yaourt
makepkg -i --asroot --noconfirm





pacman -S --noconfirm gnome gnome-extra 
pacman -S --noconfirm ttf-ubuntu-font-family ttf-liberation ttf-inconsolata ttf-droid ttf-linux-libertine ttf-dejavu ttf-bitstream-vera

systemctl enable gdm.service

if [[ $NETCONFIGFILE == "" ]]; then
	pacman -S --noconfirm  networkmanager network-manager-applet
	systemctl enable NetworkManager.service 
else
	echo "todo network"
fi

sed -i "s/\[daemon\]/\# Enable automatic login for user\n\[daemon\]\nAutomaticLogin=${NEWUSERNAME}\nAutomaticLoginEnable=True/g" /etc/gdm/custom.conf






pacman -S --noconfirm  terminator blender gimp meld gitg smartmontools firefox rsync sbt scala python2 ipython2 vlc pidgin octave gnuplot

pacman -R --noconfirm epiphany empathy gnome-chess gnome-mines gnome-sudoku gnome-tetravex gnome-robots gnome-klotski gnome-nibbles totem


/root/arch/arch-server-setup


